version: '3.7'

services:
  backup-server:
    build:
      context: .
      dockerfile: Dockerfile
      target: base
    volumes:
      - ./src:/home/node/app/src
      - ./logs:/home/node/app/logs
    container_name: backup-server
    depends_on:
      - backup-db
    expose:
      - ${PORT}
    ports:
      - ${PORT}:${PORT}
    command: npm run start
  backup-db:
    image: mongo
    volumes:
      - mongodb-backup:/data/db
volumes:
  mongodb-backup:
